Repository irenee-14/This-is-the-first-lesson, pull requests merged in 2025-09, with the labels that each got.

#30 [Feat] #23 stroy api implement
  backend/package.json
  backend/src/app.ts
  backend/src/model/common.ts
  backend/src/model/storyPrompt.ts
  backend/src/routes/stories.ts
  backend/src/types/api.ts
Labels: 📮 API, ❤️ BE

#35 [Feat]#29 잠금 배경 오픈 bottom sheet 및 toast
  frontend/package.json
  frontend/src/assets/icons/Key.svg
  frontend/src/assets/icons/key.png
  frontend/src/components/features/BackgroundUnlockSheet.tsx
  frontend/src/components/features/CardListColumn.tsx
  frontend/src/components/features/CardMediaLeft.tsx
  frontend/src/components/ui/BottomSheet.tsx
  frontend/src/components/ui/IconButton.tsx
  frontend/src/hooks/useApi.tsx
  frontend/src/hooks/useBackgroundClickHandler.tsx
  frontend/src/pages/Backgrounds.tsx
  frontend/src/styles/components/button.css
  frontend/src/types/background.ts
  frontend/tailwind.config.js
  package-lock.json
Labels: ✨ feature, 💙 FE

#38 [Feat] #31 오픈된 배경 선택 플로우 조회 api 수정
  backend/package.json
  backend/prisma/migrations/20250901070843_/migration.sql
  backend/prisma/migrations/20250902041402_/migration.sql
  backend/prisma/migrations/20250902052125_/migration.sql
  backend/prisma/schema.prisma
  backend/public/강변의 이동서점 트럭.png
  backend/public/비 오는 밤 레코드숍.png
  backend/public/유리 천장의 온실.png
  backend/public/절벽 끝 오래된 등대.png
  backend/public/폐쇄된 기숙사 옥상.png
  backend/src/app.ts
  backend/src/model/common.ts
  backend/src/model/storyPrompt.ts
  backend/src/routes/backgroundFlow.ts
  backend/src/routes/backgrounds.ts
  backend/src/routes/characters.ts
  backend/src/routes/user.ts
Labels: 📮 API, ❤️ BE

#41 [Feat] #37 chat api 연결 및 스크롤 구현
  backend/src/app.ts
  backend/src/routes/chats.ts
  backend/src/types/api.ts
  frontend/src/App.tsx
  frontend/src/assets/icons/feed.svg
  frontend/src/components/features/FloatingInputButton.tsx
  frontend/src/components/features/MyMessage.tsx
  frontend/src/components/features/OtherMessage.tsx
  frontend/src/components/layout/BottomNav.tsx
  frontend/src/hooks/useChat.tsx
  frontend/src/hooks/useTopSentinelObserver.tsx
  frontend/src/pages/Chat.tsx
  frontend/src/pages/ComponentDemo.tsx
  frontend/src/pages/FeedPage.tsx
  frontend/src/pages/Personas.tsx
  frontend/src/stores/useFlowStore.tsx
  frontend/src/types/chat.ts
  package-lock.json
Labels: ✨ feature, 📮 API, 💙 FE

#42 [Feat] #32 persona api implement
  backend/prisma/schema.prisma
  backend/src/app.ts
  backend/src/routes/personas.ts
Labels: 📮 API, ❤️ BE

#48 [Feat] #39 chat list, flow list, 해금 API 연결 및 기타 에러 처리
  backend/prisma/migrations/20250904044107_/migration.sql
  backend/src/app.ts
  backend/src/routes/backgrounds.ts
  backend/src/routes/chats.ts
  backend/src/routes/user.ts
  frontend/src/App.tsx
  frontend/src/assets/icons/Send.svg
  frontend/src/components/features/BackgroundUnlockProvider.tsx
  frontend/src/components/features/BackgroundUnlockSheet.tsx
  frontend/src/components/features/CharacterDescriptionTab.tsx
  frontend/src/components/features/CharacterInfoSection.tsx
  frontend/src/components/features/card/CardListRow.tsx
  frontend/src/components/features/card/CardMediaLeft.tsx
  frontend/src/components/features/card/CardMediaTop.tsx
  frontend/src/components/features/characterTab/BeforeChatTab.tsx
  frontend/src/components/features/characterTab/CharacterDescriptionTab.tsx
  frontend/src/components/features/characterTab/CharacterDetailTabs.tsx
  frontend/src/components/features/characterTab/CharacterInfoSection.tsx
  frontend/src/components/features/characterTab/DetailTab.tsx
  frontend/src/components/features/message/MessageActions.tsx
  frontend/src/components/features/message/MyMessage.tsx
  frontend/src/components/features/message/OtherMessage.tsx
  frontend/src/components/layout/BottomNav.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/components/ui/BottomSheet.tsx
  frontend/src/hooks/useBackgroundClickHandler.tsx
  frontend/src/hooks/useBackgroundUnlock.tsx
  frontend/src/hooks/useChatList.tsx
  frontend/src/hooks/useFlowManager.tsx
  frontend/src/main.tsx
  frontend/src/pages/Backgrounds.tsx
  frontend/src/pages/CharacterDetail.tsx
  frontend/src/pages/CharacterList.tsx
  frontend/src/pages/Chat.tsx
  frontend/src/pages/ChatList.tsx
  frontend/src/pages/Chats.tsx
  frontend/src/pages/FeedPage.tsx
  frontend/src/pages/Personas.tsx
  frontend/src/pages/Story.tsx
  frontend/src/pages/StoryDetail.tsx
  frontend/src/pages/StoryList.tsx
  frontend/src/pages/delete/ComponentDemo.tsx
  frontend/src/styles/globals.css
  frontend/src/types/background.ts
  frontend/src/types/chat.ts
  frontend/src/types/story.ts
  frontend/src/utils/scrollbarUtils.ts
  frontend/tailwind.config.js
  frontend/vite.config.ts
Labels: ✨ feature, 📮 API, 🔨 refactor, 💙 FE
